-- AlterTable
ALTER TABLE "Ansatt" ALTER COLUMN "oppdatert" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "passordHash" SET DEFAULT '',
ALTER COLUMN "tilganger" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "rolle" SET DEFAULT 'TRAFIKKLARER';

-- AlterTable
ALTER TABLE "Bedrift" ALTER COLUMN "orgNummer" SET DEFAULT '',
ALTER COLUMN "oppdatert" SET DEFAULT CURRENT_TIMESTAMP;
