global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@tms.local'
  smtp_auth_username: 'alerts@tms.local'
  smtp_auth_password: 'your-email-password'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'
  - match:
      service: tms-backend
    receiver: 'tms-alerts'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'

- name: 'critical-alerts'
  email_configs:
  - to: 'admin@tms.local'
    headers:
      Subject: '🚨 KRITISK ALARM: {{ .GroupLabels.alertname }}'
    html: |
      <h1>Kritisk alarm i TMS-systemet!</h1>
      
      <p><strong>Alarm:</strong> {{ .GroupLabels.alertname }}</p>
      <p><strong>Alvorlighetsgrad:</strong> {{ .CommonLabels.severity }}</p>
      <p><strong>Tjeneste:</strong> {{ .CommonLabels.service }}</p>
      
      <h2>Detaljer:</h2>
      <ul>
      {{ range .Alerts }}
      <li>{{ .Annotations.summary }}
        <br>Beskrivelse: {{ .Annotations.description }}
        <br>Startet: {{ .StartsAt }}</li>
      {{ end }}
      </ul>
      
      <p><a href="http://grafana.localhost:3001">Dashboard</a> | <a href="http://prometheus.localhost:9090">Prometheus</a></p>
  # slack_configs:
  # - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
  #   channel: '#tms-alerts'
  #   title: '🚨 Kritisk TMS Alarm'
  #   text: |
  #     Kritisk alarm i TMS-systemet: {{ .GroupLabels.alertname }}
  #     Alvorlighetsgrad: {{ .CommonLabels.severity }}

- name: 'warning-alerts'
  email_configs:
  - to: 'team@tms.local'
    headers:
      Subject: '⚠️ ADVARSEL: {{ .GroupLabels.alertname }}'
    html: |
      <h1>Advarsel i TMS-systemet</h1>
      
      <p><strong>Alarm:</strong> {{ .GroupLabels.alertname }}</p>
      <p><strong>Alvorlighetsgrad:</strong> {{ .CommonLabels.severity }}</p>
      
      <h2>Detaljer:</h2>
      <ul>
      {{ range .Alerts }}
      <li>{{ .Annotations.summary }}</li>
      {{ end }}
      </ul>

- name: 'tms-alerts'
  webhook_configs:
  - url: 'http://tms-backend:4000/api/alerts/webhook'
    send_resolved: true
    http_config:
      basic_auth:
        username: 'alertmanager'
        password: 'webhook_password'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance'] 