global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'tms-monitor'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # TMS Backend Application Metrics
  - job_name: 'tms-backend'
    static_configs:
      - targets: ['tms-backend:4000']
    metrics_path: '/api/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # Node Exporter - System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    scrape_timeout: 10s

  # cAdvisor - Container Metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    scrape_timeout: 10s

  # PostgreSQL Exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Nginx Exporter
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Grafana Metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # AlertManager Metrics
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    scrape_interval: 30s

  # Custom TMS Application Metrics
  - job_name: 'tms-custom-metrics'
    static_configs:
      - targets: ['tms-backend:4000']
    metrics_path: '/api/performance/metrics'
    scrape_interval: 5s
    scrape_timeout: 3s
    params:
      format: ['json']

  # TMS Security Metrics
  - job_name: 'tms-security'
    static_configs:
      - targets: ['tms-backend:4000']
    metrics_path: '/api/security/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    basic_auth:
      username: 'prometheus'
      password: 'prometheus_password'

  # TMS Database Health
  - job_name: 'tms-database-health'
    static_configs:
      - targets: ['tms-backend:4000']
    metrics_path: '/api/database/health'
    scrape_interval: 60s
    scrape_timeout: 15s

  # TMS Cache Metrics
  - job_name: 'tms-cache'
    static_configs:
      - targets: ['tms-backend:4000']
    metrics_path: '/api/cache/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s 