apiVersion: v1
kind: ServiceAccount
metadata:
  name: tms-backend
  namespace: tms
  labels:
    app: tms
    component: backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tms
  name: tms-backend-role
  labels:
    app: tms
    component: backend
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tms-backend-rolebinding
  namespace: tms
  labels:
    app: tms
    component: backend
subjects:
- kind: ServiceAccount
  name: tms-backend
  namespace: tms
roleRef:
  kind: Role
  name: tms-backend-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tms-monitoring
  namespace: tms
  labels:
    app: tms
    component: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tms-monitoring-clusterrole
  labels:
    app: tms
    component: monitoring
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tms-monitoring-clusterrolebinding
  labels:
    app: tms
    component: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tms-monitoring-clusterrole
subjects:
- kind: ServiceAccount
  name: tms-monitoring
  namespace: tms 